import { type UsgsEarthquakeGeoJson } from '@/features/earthquakes/model/usgs-geojson.types'

export const realShapedUsgsFixture: UsgsEarthquakeGeoJson = {
  type: 'FeatureCollection',
  metadata: {
    generated: 1775725954000,
    url: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_hour.geojson',
    title: 'USGS Magnitude 4.5+ Earthquakes, Past Hour',
    status: 200,
    api: '1.14.1',
    count: 2,
  },
  bbox: [-123.5, 36.5, 5.1, -121.1, 48.1, 42.2],
  features: [
    {
      type: 'Feature',
      properties: {
        mag: 4.8,
        place: 'Near San Francisco, CA',
        time: 1775725954000,
        updated: 1775725955000,
        tz: null,
        url: 'https://earthquake.usgs.gov/earthquakes/eventpage/usabc123',
        detail: 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=usabc123&format=geojson',
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: 'reviewed',
        tsunami: 0,
        sig: 354,
        net: 'us',
        code: 'abc123',
        ids: ',usabc123,',
        sources: ',us,',
        types: ',origin,phase-data,',
        nst: 54,
        dmin: 0.03,
        rms: 0.74,
        gap: 44,
        magType: 'mb',
        type: 'earthquake',
      },
      geometry: {
        type: 'Point',
        coordinates: [-122.4, 37.8, 5.1],
      },
      id: 'usabc123',
    },
    {
      type: 'Feature',
      properties: {
        mag: 5.2,
        place: 'Near Seattle, WA',
        time: 1775726954000,
        updated: 1775726955000,
        tz: null,
        url: 'https://earthquake.usgs.gov/earthquakes/eventpage/usdef456',
        detail: 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=usdef456&format=geojson',
        felt: null,
        cdi: null,
        mmi: null,
        alert: null,
        status: 'reviewed',
        tsunami: 0,
        sig: 416,
        net: 'us',
        code: 'def456',
        ids: ',usdef456,',
        sources: ',us,',
        types: ',origin,phase-data,',
        nst: 67,
        dmin: 0.11,
        rms: 0.92,
        gap: 36,
        magType: 'mww',
        type: 'earthquake',
      },
      geometry: {
        type: 'Point',
        coordinates: [-122.33, 47.61, 42.2],
      },
      id: 'usdef456',
    },
  ],
}
